// AUTO-GENERATED by astra build — do not edit.
import { startAstraServer } from '@bpjs159/adapters';
import { fileURLToPath } from 'node:url';
import '../src/server.ts';
import '../src/server.ts';

// The bundle lives at <dist>/server/server.mjs → ../ is the client build.
const distDir = process.env.ASTRA_DIST
  ?? fileURLToPath(new URL('../', import.meta.url));

startAstraServer({
  apiPrefix: "/api/astra",
  staticDir: distDir,
  port: Number(process.env.PORT ?? 3000),
});
