// AUTO-GENERATED by astrajs.dev/adapters — do not edit.
const handlerRegistry = /* @__PURE__ */ new Map();
function rpcHandler(id, fn, options = {}) {
  handlerRegistry.set(id, {
    fn,
    tags: options.tags ?? [],
    autoSync: options.autoSync ?? false,
    maxAge: options.maxAge ?? 0,
    stream: options.stream ?? false
  });
}
let rpcSecurity = {
  auth: void 0,
  maxBodyBytes: 1024 * 1024,
  exposeErrors: true
};
function payloadTooLarge() {
  return new Response(
    JSON.stringify({ error: "Request body too large" }),
    { status: 413, headers: { "Content-Type": "application/json" } }
  );
}
async function handleRPCRequest(request, id) {
  const handler2 = handlerRegistry.get(id);
  if (!handler2) {
    return new Response(
      JSON.stringify({ error: `Unknown RPC handler: ${id}` }),
      { status: 404, headers: { "Content-Type": "application/json" } }
    );
  }
  try {
    let args;
    if (request.method === "GET") {
      const url = new URL(request.url);
      args = [];
      for (let i = 0; ; i++) {
        const val = url.searchParams.get(`_${i}`);
        if (val === null) break;
        args.push(JSON.parse(val));
      }
    } else {
      const declared = Number(request.headers.get("content-length") ?? 0);
      if (Number.isFinite(declared) && declared > (rpcSecurity.maxBodyBytes ?? 1024 * 1024)) {
        return payloadTooLarge();
      }
      const body = await request.text();
      if (body.length > (rpcSecurity.maxBodyBytes ?? 1024 * 1024)) {
        return payloadTooLarge();
      }
      args = JSON.parse(body);
      if (!Array.isArray(args)) {
        args = [args];
      }
    }
    const result = await handler2.fn(...args);
    if (handler2.stream) {
      const encoder = new TextEncoder();
      const gen = result;
      const body = new ReadableStream({
        async start(controller) {
          try {
            for await (const chunk of gen) {
              if (typeof chunk === "string" && chunk.length > 0) {
                controller.enqueue(encoder.encode(chunk));
              }
            }
          } catch (err) {
            const message = err instanceof Error ? err.message : "Internal stream error";
            controller.enqueue(encoder.encode(`
[AstraJS stream error] ${message}`));
          } finally {
            controller.close();
          }
        }
      });
      const streamHeaders = {
        "Content-Type": "text/plain; charset=utf-8",
        "Cache-Control": "no-cache",
        "X-Astra-Stream": "1"
      };
      if (handler2.maxAge > 0) {
        streamHeaders["Cache-Control"] = `public, max-age=${handler2.maxAge}, stale-while-revalidate=${handler2.maxAge * 2}`;
        streamHeaders["CDN-Cache-Control"] = `max-age=${handler2.maxAge}`;
        if (handler2.tags.length > 0) {
          streamHeaders["Cache-Tag"] = handler2.tags.join(",");
        }
      }
      return new Response(body, { status: 200, headers: streamHeaders });
    }
    const headers = {
      "Content-Type": "application/json"
    };
    if (handler2.autoSync) {
      const etag = `"${hashJSON(result)}"`;
      headers["ETag"] = etag;
      headers["Cache-Control"] = "no-cache";
      if (request.headers.get("If-None-Match") === etag) {
        return new Response(null, { status: 304, headers });
      }
    }
    if (handler2.maxAge > 0) {
      headers["Cache-Control"] = `public, max-age=${handler2.maxAge}, stale-while-revalidate=${handler2.maxAge * 2}`;
      headers["CDN-Cache-Control"] = `max-age=${handler2.maxAge}`;
      if (handler2.tags.length > 0) {
        headers["Cache-Tag"] = handler2.tags.join(",");
      }
    }
    return new Response(JSON.stringify(result), {
      status: 200,
      headers
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : "Internal RPC error";
    console.error(`[AstraJS RPC] Handler "${id}" failed:`, err);
    return new Response(
      JSON.stringify({
        error: message
      }),
      { status: 500, headers: { "Content-Type": "application/json" } }
    );
  }
}
function hashJSON(value) {
  const str = JSON.stringify(value);
  let hash = 2166136261;
  for (let i = 0; i < str.length; i++) {
    hash ^= str.charCodeAt(i);
    hash = Math.imul(hash, 16777619);
  }
  return (hash >>> 0).toString(16).padStart(8, "0");
}
const swrCache = /* @__PURE__ */ new Map();
if (typeof window !== "undefined") {
  window.addEventListener("focus", () => {
    for (const [, entry] of swrCache) {
      if (entry.options.revalidateOnFocus !== false && !entry.isValidating) {
        const swrEntry = entry;
        swrEntry.isValidating = true;
        swrEntry.pendingPromise = swrEntry.fetcher();
        swrEntry.pendingPromise.then((fresh) => {
          swrEntry.data = fresh;
          swrEntry.fetchedAt = Date.now();
        }).catch(() => {
        }).finally(() => {
          swrEntry.isValidating = false;
          swrEntry.pendingPromise = null;
        });
      }
    }
  });
  window.addEventListener("online", () => {
    for (const [, entry] of swrCache) {
      if (!entry.isValidating) {
        const swrEntry = entry;
        swrEntry.isValidating = true;
        swrEntry.pendingPromise = swrEntry.fetcher();
        swrEntry.pendingPromise.then((fresh) => {
          swrEntry.data = fresh;
          swrEntry.fetchedAt = Date.now();
        }).catch(() => {
        }).finally(() => {
          swrEntry.isValidating = false;
          swrEntry.pendingPromise = null;
        });
      }
    }
  });
}
function server(configOrFn, fn) {
  if (typeof configOrFn === "function") {
    return configOrFn;
  }
  throw new Error(
    "[AstraJS] server() macro was not transformed by the compiler. Make sure astrajs.dev/compiler is in your vite.config.ts plugins."
  );
}
const STORE_SYMBOL = Symbol("astra-store");
const rawDeps = /* @__PURE__ */ new WeakMap();
const rawToProxy = /* @__PURE__ */ new WeakMap();
const proxyToRaw = /* @__PURE__ */ new WeakMap();
const pendingNotifications = /* @__PURE__ */ new Set();
let microtaskScheduled = false;
function scheduleMicrotaskFlush() {
  if (microtaskScheduled) return;
  microtaskScheduled = true;
  queueMicrotask(() => {
    microtaskScheduled = false;
    flushPending();
  });
}
function trigger(raw, prop) {
  const propMap = rawDeps.get(raw);
  if (!propMap) return;
  const subscribers = propMap.get(prop);
  if (!subscribers || subscribers.size === 0) return;
  for (const sub of subscribers) {
    pendingNotifications.add(sub);
  }
  scheduleMicrotaskFlush();
}
function flushPending() {
  while (pendingNotifications.size > 0) {
    const snapshot = [...pendingNotifications];
    pendingNotifications.clear();
    for (const sub of snapshot) {
      sub();
    }
  }
}
function isProxyable(value) {
  if (Array.isArray(value)) return true;
  const proto = Object.getPrototypeOf(value);
  return proto === Object.prototype || proto === null;
}
function isArrayIndex(prop) {
  const n = Number(prop);
  return Number.isInteger(n) && n >= 0 && n < 4294967295;
}
function createReactiveProxy(raw) {
  const existing = rawToProxy.get(raw);
  if (existing) return existing;
  const handler2 = {
    get(target, prop, receiver) {
      if (prop === STORE_SYMBOL) return true;
      const value = Reflect.get(target, prop, receiver);
      if (value !== null && typeof value === "object" && !ArrayBuffer.isView(value) && isProxyable(value)) {
        const existingProxy = rawToProxy.get(value);
        if (existingProxy) return existingProxy;
        return createReactiveProxy(value);
      }
      return value;
    },
    set(target, prop, value, receiver) {
      const oldValue = Reflect.get(target, prop, receiver);
      if (oldValue === value) return true;
      const isArrayIndexWrite = Array.isArray(target) && typeof prop === "string" && isArrayIndex(prop);
      const oldLength = isArrayIndexWrite ? Reflect.get(target, "length", receiver) : 0;
      const result = Reflect.set(target, prop, value, receiver);
      trigger(target, prop);
      if (isArrayIndexWrite && Number(prop) >= oldLength) {
        trigger(target, "length");
      }
      return result;
    },
    deleteProperty(target, prop) {
      const had = Object.prototype.hasOwnProperty.call(target, prop);
      const result = Reflect.deleteProperty(target, prop);
      if (had) {
        trigger(target, prop);
      }
      return result;
    }
    // Support for array methods: ensure array mutations trigger correctly
    // The `ownKeys` and `has` traps don't need explicit track/trigger since
    // they are used by Object.keys/in which don't create reactive deps by default.
  };
  const proxy = new Proxy(raw, handler2);
  rawToProxy.set(raw, proxy);
  proxyToRaw.set(proxy, raw);
  return proxy;
}
function store(initialState, _options) {
  if (typeof initialState === "function") {
    const raw = {};
    const proxy = createReactiveProxy(raw);
    const result = initialState(proxy);
    Object.assign(raw, result);
    for (const key of Object.keys(result)) {
      if (typeof result[key] === "function") {
        raw[key] = result[key];
      }
    }
    return proxy;
  }
  if (typeof initialState !== "object" || initialState === null) {
    throw new TypeError(
      `[AstraJS] store() expects a plain object, received ${typeof initialState}`
    );
  }
  return createReactiveProxy(initialState);
}
const activeCleanups = /* @__PURE__ */ new Map();
let observer = null;
function getObserver() {
  if (typeof MutationObserver === "undefined" || typeof document === "undefined") {
    return null;
  }
  if (!observer) {
    observer = new MutationObserver((mutations) => {
      for (const mutation of mutations) {
        for (const node of mutation.removedNodes) {
          if (typeof HTMLElement !== "undefined" && node instanceof HTMLElement) {
            const cleanup = activeCleanups.get(node);
            if (cleanup) {
              cleanup();
              activeCleanups.delete(node);
            }
            node.querySelectorAll("[data-astra-lifecycle]").forEach((el) => {
              const c = activeCleanups.get(el);
              if (c) {
                c();
                activeCleanups.delete(el);
              }
            });
          }
        }
      }
    });
    observer.observe(document.body, { childList: true, subtree: true });
  }
  return observer;
}
if (typeof MutationObserver !== "undefined" && typeof document !== "undefined") {
  getObserver();
}
function css(_strings, ..._values) {
  return new Proxy({}, {
    get(_target, prop) {
      return prop;
    }
  });
}
css`
  /* ── Card ─────────────────────────────────────────────────────── */
  .card {
    background: #1e293b;
    border: 1px solid #334155;
    border-radius: 20px;
    padding: 0;
    max-width: 620px;
    width: 100%;
    overflow: hidden;
    box-shadow: 0 1px 3px rgba(0,0,0,.3), 0 8px 32px rgba(0,0,0,.15);
  }

  /* ── Header ───────────────────────────────────────────────────── */
  .header {
    padding: 28px 32px 20px;
    border-bottom: 1px solid #334155;
    background: linear-gradient(135deg, rgba(99,102,241,.06) 0%, transparent 60%);
  }
  .header h1 {
    font-size: 1.3rem;
    font-weight: 700;
    color: #f1f5f9;
    margin-bottom: 5px;
    letter-spacing: -.01em;
  }
  .header p {
    font-size: .8rem;
    color: #64748b;
    line-height: 1.5;
  }
  .header code {
    background: rgba(99,102,241,.15);
    color: #818cf8;
    padding: 1px 7px;
    border-radius: 4px;
    font-size: .78rem;
    font-weight: 500;
  }

  /* ── Body ─────────────────────────────────────────────────────── */
  .body {
    padding: 24px 32px 28px;
  }

  /* ── Flow Diagram ─────────────────────────────────────────────── */
  .flow {
    display: flex;
    gap: 0;
    margin-bottom: 24px;
    align-items: center;
    justify-content: center;
    flex-wrap: wrap;
  }
  .flowStep {
    background: #0f172a;
    border: 1px solid #334155;
    border-radius: 10px;
    padding: 10px 16px;
    text-align: center;
    min-width: 75px;
    transition: border-color .2s, background .2s;
  }
  .flowStep:hover {
    border-color: #475569;
    background: #111827;
  }
  .flowStep strong {
    color: #818cf8;
    display: block;
    font-size: .7rem;
    text-transform: uppercase;
    letter-spacing: .05em;
    margin-bottom: 2px;
  }
  .flowStep span {
    color: #94a3b8;
    font-size: .78rem;
    font-family: 'JetBrains Mono', 'Fira Code', monospace;
  }
  .flowArrow {
    color: #475569;
    font-size: 1.1rem;
    margin: 0 6px;
  }

  /* ── Buttons ──────────────────────────────────────────────────── */
  .actions {
    display: flex;
    gap: 8px;
    margin-bottom: 20px;
    flex-wrap: wrap;
    align-items: center;
  }
  .btnFetch {
    padding: 9px 18px;
    border: none;
    border-radius: 10px;
    font-weight: 600;
    font-size: .82rem;
    cursor: pointer;
    background: #6366f1;
    color: #fff;
    transition: filter .15s, transform .1s, box-shadow .15s;
    display: flex;
    align-items: center;
    gap: 6px;
  }
  .btnFetch:hover {
    filter: brightness(1.12);
    box-shadow: 0 2px 12px rgba(99,102,241,.35);
  }
  .btnFetch:active {
    transform: scale(.97);
  }
  .btnClear {
    padding: 9px 16px;
    border: 1px solid #334155;
    border-radius: 10px;
    font-weight: 500;
    font-size: .8rem;
    cursor: pointer;
    background: transparent;
    color: #64748b;
    transition: border-color .15s, color .15s, transform .1s;
  }
  .btnClear:hover {
    border-color: #64748b;
    color: #cbd5e1;
  }
  .btnClear:active {
    transform: scale(.97);
  }

  /* ── Result Box (log container) ───────────────────────────────── */
  .resultBox {
    background: #0f172a;
    border: 1px solid #334155;
    border-radius: 12px;
    padding: 14px;
    min-height: 80px;
    font-family: 'JetBrains Mono', 'Fira Code', 'SF Mono', monospace;
    font-size: .8rem;
    line-height: 1.6;
    overflow-x: auto;
  }

  /* ── Empty State ──────────────────────────────────────────────── */
  .emptyState {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    padding: 40px 0;
    color: #475569;
    font-family: system-ui, sans-serif;
    font-size: .84rem;
    font-weight: 500;
    gap: 8px;
  }
  .emptyIcon {
    font-size: 1.6rem;
    opacity: .5;
  }

  /* ── Log Entry ────────────────────────────────────────────────── */
  .logEntry {
    display: flex;
    align-items: flex-start;
    gap: 10px;
    padding: 10px 12px;
    border-radius: 8px;
    margin-bottom: 6px;
    background: #1e293b;
    border: 1px solid transparent;
    transition: border-color .2s;
  }
  .logEntry:last-child {
    margin-bottom: 0;
  }
  .logEntry:hover {
    border-color: #334155;
  }
  .logStatus {
    width: 8px;
    height: 8px;
    border-radius: 50%;
    margin-top: 6px;
    flex-shrink: 0;
  }
  .logLoading { background: #fbbf24; box-shadow: 0 0 8px rgba(251,191,36,.5); }
  .logSuccess { background: #34d399; box-shadow: 0 0 8px rgba(52,211,153,.4); }
  .logError   { background: #f87171; box-shadow: 0 0 8px rgba(248,113,113,.4); }

  .logBody { flex: 1; min-width: 0; }

  .logMeta {
    display: flex;
    align-items: center;
    gap: 8px;
    margin-bottom: 4px;
    flex-wrap: wrap;
  }
  .logTime {
    color: #64748b;
    font-size: .72rem;
    font-family: system-ui, sans-serif;
  }
  .logEndpoint {
    color: #a5b4fc;
    font-weight: 600;
    font-size: .78rem;
  }
  .logTag {
    font-size: .65rem;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: .05em;
    padding: 1px 6px;
    border-radius: 3px;
    font-family: system-ui, sans-serif;
  }
  .logTagPending { background: rgba(251,191,36,.15); color: #fbbf24; }
  .logTagOk      { background: rgba(52,211,153,.12); color: #34d399; }
  .logTagErr     { background: rgba(248,113,113,.12); color: #f87171; }

  .logArgs {
    color: #64748b;
    font-size: .73rem;
    margin-bottom: 4px;
    word-break: break-all;
  }
  .logResult {
    font-size: .73rem;
    padding: 6px 10px;
    border-radius: 5px;
    word-break: break-all;
    white-space: pre-wrap;
    max-height: 80px;
    overflow-y: auto;
  }
  .logResultSuccess { background: #0f172a; color: #6ee7b7; }
  .logResultError   { background: #0f172a; color: #fca5a5; }
  .logResultLoading { background: #0f172a; color: #fcd34d; }
`;
store({ logs: [], counter: 0 });
const createUser = server(async (name, email) => {
  return { ok: true, data: { id: crypto.randomUUID(), name, email } };
});
const updateProduct = server(async (productId, updates) => {
  return { ok: true, data: { id: productId, price: updates.price } };
});
const deleteOrder = server(async (orderId) => {
  const existed = Math.random() > 0.3;
  return { ok: true, data: { id: orderId, deleted: existed } };
});
rpcHandler("createUser", createUser);
rpcHandler("updateProduct", updateProduct);
rpcHandler("deleteOrder", deleteOrder);
const apiPrefix = "/api/astra";
async function handler(req, res) {
  try {
    const url = new URL(req.url ?? "/", `http://${req.headers.host ?? "localhost"}`);
    if (url.pathname !== apiPrefix && !url.pathname.startsWith(apiPrefix + "/")) {
      res.statusCode = 404;
      res.setHeader("Content-Type", "application/json");
      res.end(JSON.stringify({ error: "Not found" }));
      return;
    }
    const handlerId = url.pathname.slice(apiPrefix.length + 1);
    let body;
    if (req.method !== "GET" && req.method !== "HEAD") {
      const chunks = [];
      for await (const c of req) chunks.push(c);
      body = Buffer.concat(chunks).toString();
    }
    const webRequest = new Request(url.toString(), {
      method: req.method,
      headers: Object.entries(req.headers).reduce(
        (acc, [k, v]) => ({
          ...acc,
          [k]: Array.isArray(v) ? v.join(", ") : String(v ?? "")
        }),
        {}
      ),
      body
    });
    const response = await handleRPCRequest(webRequest, handlerId);
    res.statusCode = response.status;
    response.headers.forEach((value, key) => res.setHeader(key, value));
    if (response.headers.get("x-astra-stream") === "1" && response.body) {
      for await (const chunk of response.body) res.write(Buffer.from(chunk));
      res.end();
    } else {
      res.end(Buffer.from(await response.arrayBuffer()));
    }
  } catch (err) {
    res.statusCode = 500;
    res.setHeader("Content-Type", "application/json");
    res.end(JSON.stringify({ error: err instanceof Error ? err.message : String(err) }));
  }
}
export {
  handler as default
};
