// AUTO-GENERATED by astra build — do not edit.
import { handleRPCRequest } from 'astrajs.dev/server';
import '../src/server.ts';
import '../src/server.ts';
import '../src/server.ts';


const apiPrefix = "/examples/deploy/03-cloudflare/api/astra";

// Cloudflare Worker / Pages Function — single server registry with the
// compiled handler modules above.
export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    if (url.pathname === apiPrefix || url.pathname.startsWith(apiPrefix + '/')) {
      return handleRPCRequest(request, url.pathname.slice(apiPrefix.length + 1));
    }
    const notFound = new Response(JSON.stringify({ error: 'Not found' }), {
      status: 404,
      headers: { 'Content-Type': 'application/json' },
    });
    // Cloudflare Pages exposes static assets via the ASSETS binding.
    if (env?.ASSETS) {
      return env.ASSETS.fetch(request).catch(() => notFound);
    }
    return notFound;
  },
};
