// AUTO-GENERATED by astra build — do not edit.
import { createCloudflareHandler } from '@astrajs/adapters/edge';
import '../src/server.ts';
import '../src/server.ts';
import '../src/server.ts';

export default createCloudflareHandler({ apiPrefix: "/api/astra" });
