/**
 * AI 03 — Build-time AI UI.
 *
 * `faq` is a folded constant: no fetch, no async, no runtime model call.
 */
import { component } from 'astrajs.dev/core';
import { faq } from './server.js';

interface FaqItem {
  q: string;
  a: string;
}

const css = `
  *{margin:0;padding:0;box-sizing:border-box}
  body{font-family:system-ui,-apple-system,sans-serif;background:#0f172a;color:#e2e8f0;padding:48px 20px}
  .wrap{max-width:720px;margin:0 auto}
  h1{font-size:1.4rem;font-weight:800;letter-spacing:-.02em;margin-bottom:6px}
  .sub{font-size:.82rem;color:#64748b;margin-bottom:28px;line-height:1.7}
  .sub code{background:rgba(245,158,11,.15);color:#fbbf24;padding:1px 7px;border-radius:4px}
  .faq{display:flex;flex-direction:column;gap:12px}
  .card{background:#1e293b;border:1px solid #334155;border-radius:12px;padding:16px 20px}
  .card h3{font-size:.9rem;color:#e2e8f0;margin-bottom:6px}
  .card p{font-size:.82rem;color:#94a3b8;line-height:1.7}
  .note{margin-top:24px;padding:14px 18px;background:rgba(245,158,11,.07);border:1px solid rgba(245,158,11,.18);border-radius:12px;font-size:.78rem;color:#94a3b8;line-height:1.7}
`;

/** The folded value is data, not a function (same pattern as server pre-build). */
const items = (faq as unknown as FaqItem[] | { text?: string }) as FaqItem[];
const faqs: FaqItem[] = Array.isArray(items)
  ? items.filter((i) => i && typeof i.q === 'string')
  : [{ q: 'Build-time AI', a: (items as unknown as { text?: string }).text ?? '' }];

export const BuildTimeApp = component(() => (
  <div class="wrap">
    <style>{css}</style>
    <h1>AI 03 — Build-time AI</h1>
    <p class="sub">
      These FAQs were generated by <code>ai({'{ type: \'pre-build\' }'})</code> during
      <code>astra build</code> and folded into the bundle. Check <code>dist/assets/*.js</code>:
      the answers are there, the fetch is not.
    </p>

    <div class="faq">
      {faqs.map((item) => (
        <div class="card">
          <h3>{item.q}</h3>
          <p>{item.a}</p>
        </div>
      ))}
    </div>

    <div class="note">
      Unchanged prompts are cached in <code>.astra/ai-cache.json</code> — rebuilding
      costs zero tokens until the prompt changes.
    </div>
  </div>
));
