// AUTO-GENERATED by astrajs.dev/adapters — do not edit.
const handlerRegistry = /* @__PURE__ */ new Map();
function rpcHandler(id, fn, options = {}) {
  handlerRegistry.set(id, {
    fn,
    tags: options.tags ?? [],
    autoSync: options.autoSync ?? false,
    maxAge: options.maxAge ?? 0,
    stream: options.stream ?? false
  });
}
let rpcSecurity = {
  auth: void 0,
  maxBodyBytes: 1024 * 1024,
  exposeErrors: true
};
function payloadTooLarge() {
  return new Response(
    JSON.stringify({ error: "Request body too large" }),
    { status: 413, headers: { "Content-Type": "application/json" } }
  );
}
async function handleRPCRequest(request, id) {
  const handler2 = handlerRegistry.get(id);
  if (!handler2) {
    return new Response(
      JSON.stringify({ error: `Unknown RPC handler: ${id}` }),
      { status: 404, headers: { "Content-Type": "application/json" } }
    );
  }
  try {
    let args;
    if (request.method === "GET") {
      const url = new URL(request.url);
      args = [];
      for (let i = 0; ; i++) {
        const val = url.searchParams.get(`_${i}`);
        if (val === null) break;
        args.push(JSON.parse(val));
      }
    } else {
      const declared = Number(request.headers.get("content-length") ?? 0);
      if (Number.isFinite(declared) && declared > (rpcSecurity.maxBodyBytes ?? 1024 * 1024)) {
        return payloadTooLarge();
      }
      const body = await request.text();
      if (body.length > (rpcSecurity.maxBodyBytes ?? 1024 * 1024)) {
        return payloadTooLarge();
      }
      args = JSON.parse(body);
      if (!Array.isArray(args)) {
        args = [args];
      }
    }
    const result = await handler2.fn(...args);
    if (handler2.stream) {
      const encoder = new TextEncoder();
      const gen = result;
      const body = new ReadableStream({
        async start(controller) {
          try {
            for await (const chunk of gen) {
              if (typeof chunk === "string" && chunk.length > 0) {
                controller.enqueue(encoder.encode(chunk));
              }
            }
          } catch (err) {
            const message = err instanceof Error ? err.message : "Internal stream error";
            controller.enqueue(encoder.encode(`
[AstraJS stream error] ${message}`));
          } finally {
            controller.close();
          }
        }
      });
      const streamHeaders = {
        "Content-Type": "text/plain; charset=utf-8",
        "Cache-Control": "no-cache",
        "X-Astra-Stream": "1"
      };
      if (handler2.maxAge > 0) {
        streamHeaders["Cache-Control"] = `public, max-age=${handler2.maxAge}, stale-while-revalidate=${handler2.maxAge * 2}`;
        streamHeaders["CDN-Cache-Control"] = `max-age=${handler2.maxAge}`;
        if (handler2.tags.length > 0) {
          streamHeaders["Cache-Tag"] = handler2.tags.join(",");
        }
      }
      return new Response(body, { status: 200, headers: streamHeaders });
    }
    const headers = {
      "Content-Type": "application/json"
    };
    if (handler2.autoSync) {
      const etag = `"${hashJSON(result)}"`;
      headers["ETag"] = etag;
      headers["Cache-Control"] = "no-cache";
      if (request.headers.get("If-None-Match") === etag) {
        return new Response(null, { status: 304, headers });
      }
    }
    if (handler2.maxAge > 0) {
      headers["Cache-Control"] = `public, max-age=${handler2.maxAge}, stale-while-revalidate=${handler2.maxAge * 2}`;
      headers["CDN-Cache-Control"] = `max-age=${handler2.maxAge}`;
      if (handler2.tags.length > 0) {
        headers["Cache-Tag"] = handler2.tags.join(",");
      }
    }
    return new Response(JSON.stringify(result), {
      status: 200,
      headers
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : "Internal RPC error";
    console.error(`[AstraJS RPC] Handler "${id}" failed:`, err);
    return new Response(
      JSON.stringify({
        error: message
      }),
      { status: 500, headers: { "Content-Type": "application/json" } }
    );
  }
}
function hashJSON(value) {
  const str = JSON.stringify(value);
  let hash = 2166136261;
  for (let i = 0; i < str.length; i++) {
    hash ^= str.charCodeAt(i);
    hash = Math.imul(hash, 16777619);
  }
  return (hash >>> 0).toString(16).padStart(8, "0");
}
const swrCache = /* @__PURE__ */ new Map();
if (typeof window !== "undefined") {
  window.addEventListener("focus", () => {
    for (const [, entry] of swrCache) {
      if (entry.options.revalidateOnFocus !== false && !entry.isValidating) {
        const swrEntry = entry;
        swrEntry.isValidating = true;
        swrEntry.pendingPromise = swrEntry.fetcher();
        swrEntry.pendingPromise.then((fresh) => {
          swrEntry.data = fresh;
          swrEntry.fetchedAt = Date.now();
        }).catch(() => {
        }).finally(() => {
          swrEntry.isValidating = false;
          swrEntry.pendingPromise = null;
        });
      }
    }
  });
  window.addEventListener("online", () => {
    for (const [, entry] of swrCache) {
      if (!entry.isValidating) {
        const swrEntry = entry;
        swrEntry.isValidating = true;
        swrEntry.pendingPromise = swrEntry.fetcher();
        swrEntry.pendingPromise.then((fresh) => {
          swrEntry.data = fresh;
          swrEntry.fetchedAt = Date.now();
        }).catch(() => {
        }).finally(() => {
          swrEntry.isValidating = false;
          swrEntry.pendingPromise = null;
        });
      }
    }
  });
}
function server(configOrFn, fn) {
  if (typeof configOrFn === "function") {
    return configOrFn;
  }
  throw new Error(
    "[AstraJS] server() macro was not transformed by the compiler. Make sure astrajs.dev/compiler is in your vite.config.ts plugins."
  );
}
const activeCleanups = /* @__PURE__ */ new Map();
let observer = null;
function getObserver() {
  if (typeof MutationObserver === "undefined" || typeof document === "undefined") {
    return null;
  }
  if (!observer) {
    observer = new MutationObserver((mutations) => {
      for (const mutation of mutations) {
        for (const node of mutation.removedNodes) {
          if (typeof HTMLElement !== "undefined" && node instanceof HTMLElement) {
            const cleanup = activeCleanups.get(node);
            if (cleanup) {
              cleanup();
              activeCleanups.delete(node);
            }
            node.querySelectorAll("[data-astra-lifecycle]").forEach((el) => {
              const c = activeCleanups.get(el);
              if (c) {
                c();
                activeCleanups.delete(el);
              }
            });
          }
        }
      }
    });
    observer.observe(document.body, { childList: true, subtree: true });
  }
  return observer;
}
if (typeof MutationObserver !== "undefined" && typeof document !== "undefined") {
  getObserver();
}
const getDashboardStats = server(async () => {
  return {
    totalUsers: 12400 + Math.floor(Math.random() * 200),
    totalOrders: 3800 + Math.floor(Math.random() * 300),
    revenue: 95600 + Math.floor(Math.random() * 5e3),
    serverTimestamp: (/* @__PURE__ */ new Date()).toISOString(),
    serverId: crypto.randomUUID().slice(0, 8)
  };
});
rpcHandler("getDashboardStats", getDashboardStats);
const apiPrefix = "/api/astra";
async function handler(req, res) {
  try {
    const url = new URL(req.url ?? "/", `http://${req.headers.host ?? "localhost"}`);
    if (url.pathname !== apiPrefix && !url.pathname.startsWith(apiPrefix + "/")) {
      res.statusCode = 404;
      res.setHeader("Content-Type", "application/json");
      res.end(JSON.stringify({ error: "Not found" }));
      return;
    }
    const handlerId = url.pathname.slice(apiPrefix.length + 1);
    let body;
    if (req.method !== "GET" && req.method !== "HEAD") {
      const chunks = [];
      for await (const c of req) chunks.push(c);
      body = Buffer.concat(chunks).toString();
    }
    const webRequest = new Request(url.toString(), {
      method: req.method,
      headers: Object.entries(req.headers).reduce(
        (acc, [k, v]) => ({
          ...acc,
          [k]: Array.isArray(v) ? v.join(", ") : String(v ?? "")
        }),
        {}
      ),
      body
    });
    const response = await handleRPCRequest(webRequest, handlerId);
    res.statusCode = response.status;
    response.headers.forEach((value, key) => res.setHeader(key, value));
    if (response.headers.get("x-astra-stream") === "1" && response.body) {
      for await (const chunk of response.body) res.write(Buffer.from(chunk));
      res.end();
    } else {
      res.end(Buffer.from(await response.arrayBuffer()));
    }
  } catch (err) {
    res.statusCode = 500;
    res.setHeader("Content-Type", "application/json");
    res.end(JSON.stringify({ error: err instanceof Error ? err.message : String(err) }));
  }
}
export {
  handler as default
};
