/**
 * astra build — production build with deployment adapters.
 *
 * Pipeline:
 *   1. vite build                      → client bundle + manifests (dist/)
 *   2. dist/astra-server-modules.json  → handler id → defining module map
 *   3. .astra/server-entry.ts          → imports the real handler modules
 *                                         (closures with module scope) plus
 *                                         the adapter shell
 *   4. vite build --ssr                → single-file server bundle
 *   5. adapter emitter                 → platform files:
 *                                         node       dist/server/server.mjs + Dockerfile
 *                                         vercel     api/astra.mjs + vercel.json
 *                                         cloudflare dist/_worker.js + wrangler.toml
 */
import { spawn } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { createRequire } from 'node:module';
import { colors, paint } from './colors.js';
import { findBin } from './run.js';

const ADAPTERS = ['static', 'node', 'vercel', 'cloudflare'];

/** Generated entry templates — one per adapter. */
const TEMPLATES = {
  node(imports, apiPrefix, aiImport = '') {
    return `// AUTO-GENERATED by astra build — do not edit.
import { createServer } from 'node:http';
import { existsSync, statSync, readFileSync } from 'node:fs';
import { extname, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import { handleRPCRequest } from 'astrajs.dev/server';
${imports}
${aiImport}

const apiPrefix = ${JSON.stringify(apiPrefix)};
// The bundle lives at <dist>/server/server.mjs → ../ is the client build.
const distDir = process.env.ASTRA_DIST
  ?? fileURLToPath(new URL('../', import.meta.url));
const port = Number(process.env.PORT ?? 3000);

const MIME_TYPES = {
  '.html': 'text/html; charset=utf-8',
  '.js': 'text/javascript',
  '.mjs': 'text/javascript',
  '.css': 'text/css',
  '.json': 'application/json',
  '.map': 'application/json',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.webp': 'image/webp',
  '.gif': 'image/gif',
  '.svg': 'image/svg+xml',
  '.ico': 'image/x-icon',
  '.woff': 'font/woff',
  '.woff2': 'font/woff2',
  '.ttf': 'font/ttf',
  '.txt': 'text/plain; charset=utf-8',
};

// Static file lookup with path-traversal protection.
function findStatic(pathname) {
  const rel = pathname === '/' ? 'index.html' : pathname.replace(/^\\/+/, '');
  if (rel.includes('..') || rel.includes('\\0')) return null;
  const base = resolve(distDir);
  let abs = resolve(base, rel);
  if (abs !== base && !abs.startsWith(base + sep)) return null;
  try {
    // Directories (e.g. prerendered /products/p2/) resolve to index.html.
    if (existsSync(abs) && statSync(abs).isDirectory()) {
      const index = resolve(abs, 'index.html');
      if (index !== abs && !index.startsWith(abs + sep)) return null;
      abs = index;
    }
    if (!existsSync(abs) || !statSync(abs).isFile()) return null;
  } catch {
    return null;
  }
  return {
    abs,
    type: MIME_TYPES[extname(abs).toLowerCase()] ?? 'application/octet-stream',
  };
}

// One server instance: the compiled handler modules and the RPC dispatch both
// resolve 'astrajs.dev/server' through the same module graph, so rpcHandler()
// registrations and handleRPCRequest() share a single registry.
createServer(async (req, res) => {
  try {
    const url = new URL(req.url, 'http://127.0.0.1');

    if (url.pathname === apiPrefix || url.pathname.startsWith(apiPrefix + '/')) {
      const handlerId = url.pathname.slice(apiPrefix.length + 1);
      let body;
      if (req.method !== 'GET' && req.method !== 'HEAD') {
        const chunks = [];
        for await (const c of req) chunks.push(c);
        body = Buffer.concat(chunks).toString();
      }
      const webRequest = new Request(url.toString(), {
        method: req.method,
        headers: Object.entries(req.headers).reduce(
          (acc, [k, v]) => ({
            ...acc,
            [k]: Array.isArray(v) ? v.join(', ') : String(v ?? ''),
          }),
          {}
        ),
        body,
      });
      const response = await handleRPCRequest(webRequest, handlerId);
      res.statusCode = response.status;
      response.headers.forEach((value, key) => res.setHeader(key, value));
      // Streaming handlers (aiStream) must be piped token-by-token.
      if (response.headers.get('x-astra-stream') === '1' && response.body) {
        for await (const chunk of response.body) {
          res.write(Buffer.from(chunk));
        }
        res.end();
      } else {
        res.end(Buffer.from(await response.arrayBuffer()));
      }
      return;
    }

    const file = findStatic(url.pathname);
    if (file) {
      res.statusCode = 200;
      res.setHeader('Content-Type', file.type);
      res.setHeader(
        'Cache-Control',
        url.pathname.startsWith('/assets/')
          ? 'public, max-age=31536000, immutable'
          : 'public, max-age=0, must-revalidate'
      );
      res.end(readFileSync(file.abs));
      return;
    }

    res.statusCode = 404;
    res.setHeader('Content-Type', 'application/json');
    res.end(JSON.stringify({ error: 'Not found' }));
  } catch (err) {
    res.statusCode = 500;
    res.setHeader('Content-Type', 'application/json');
    res.end(
      JSON.stringify({ error: err instanceof Error ? err.message : String(err) })
    );
  }
}).listen(port, '0.0.0.0', () => {
  console.log('[AstraJS] server listening on http://0.0.0.0:' + port);
  console.log(
    '[AstraJS] RPC prefix: ' + apiPrefix + ' · static: ' + resolve(distDir)
  );
});
`;
  },
  vercel(imports, apiPrefix, aiImport = '') {
    return `// AUTO-GENERATED by astra build — do not edit.
import { handleRPCRequest } from 'astrajs.dev/server';
${imports}
${aiImport}

const apiPrefix = ${JSON.stringify(apiPrefix)};

// Node-style (req, res) handler — single server registry with the compiled
// handler modules above (all resolve 'astrajs.dev/server' in one graph).
export default async function handler(req, res) {
  try {
    const url = new URL(req.url ?? '/', \`http://\${req.headers.host ?? 'localhost'}\`);
    if (url.pathname !== apiPrefix && !url.pathname.startsWith(apiPrefix + '/')) {
      res.statusCode = 404;
      res.setHeader('Content-Type', 'application/json');
      res.end(JSON.stringify({ error: 'Not found' }));
      return;
    }
    const handlerId = url.pathname.slice(apiPrefix.length + 1);
    let body;
    if (req.method !== 'GET' && req.method !== 'HEAD') {
      const chunks = [];
      for await (const c of req) chunks.push(c);
      body = Buffer.concat(chunks).toString();
    }
    const webRequest = new Request(url.toString(), {
      method: req.method,
      headers: Object.entries(req.headers).reduce(
        (acc, [k, v]) => ({
          ...acc,
          [k]: Array.isArray(v) ? v.join(', ') : String(v ?? ''),
        }),
        {}
      ),
      body,
    });
    const response = await handleRPCRequest(webRequest, handlerId);
    res.statusCode = response.status;
    response.headers.forEach((value, key) => res.setHeader(key, value));
    if (response.headers.get('x-astra-stream') === '1' && response.body) {
      for await (const chunk of response.body) res.write(Buffer.from(chunk));
      res.end();
    } else {
      res.end(Buffer.from(await response.arrayBuffer()));
    }
  } catch (err) {
    res.statusCode = 500;
    res.setHeader('Content-Type', 'application/json');
    res.end(JSON.stringify({ error: err instanceof Error ? err.message : String(err) }));
  }
}
`;
  },
  cloudflare(imports, apiPrefix, aiImport = '') {
    return `// AUTO-GENERATED by astra build — do not edit.
import { handleRPCRequest } from 'astrajs.dev/server';
${imports}
${aiImport}

const apiPrefix = ${JSON.stringify(apiPrefix)};

// Cloudflare Worker / Pages Function — single server registry with the
// compiled handler modules above.
export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    if (url.pathname === apiPrefix || url.pathname.startsWith(apiPrefix + '/')) {
      return handleRPCRequest(request, url.pathname.slice(apiPrefix.length + 1));
    }
    const notFound = new Response(JSON.stringify({ error: 'Not found' }), {
      status: 404,
      headers: { 'Content-Type': 'application/json' },
    });
    // Cloudflare Pages exposes static assets via the ASSETS binding.
    if (env?.ASSETS) {
      return env.ASSETS.fetch(request).catch(() => notFound);
    }
    return notFound;
  },
};
`;
  },
};

const log = (msg) => console.log(`${paint('◇', colors.purple)} ${msg}`);

/** Reads astra.config.json from the project root. */
function readProjectConfig(root) {
  try {
    const raw = JSON.parse(fs.readFileSync(path.join(root, 'astra.config.json'), 'utf-8'));
    const out = {};
    if (typeof raw?.adapter === 'string') out.adapter = raw.adapter;
    if (typeof raw?.apiPrefix === 'string') out.apiPrefix = raw.apiPrefix;
    if (typeof raw?.ai === 'object' && raw.ai !== null) out.ai = raw.ai;
    return out;
  } catch {
    return {};
  }
}

/** Reads a JSON file, returning null when missing/invalid. */
function readJson(file) {
  try {
    return JSON.parse(fs.readFileSync(file, 'utf-8'));
  } catch {
    return null;
  }
}

/** Resolves a package entry through node_modules, walking up from `root`. */
function resolveProjectPackage(root, name) {
  // Separate the bare package name from a subpath (e.g. 'astrajs.dev/adapters').
  const base = name.startsWith('@')
    ? name.split('/').slice(0, 2).join('/')
    : name.split('/')[0];
  let dir = root;
  for (;;) {
    const pkgPath = path.join(dir, 'node_modules', base, 'package.json');
    if (fs.existsSync(pkgPath)) {
      const require = createRequire(path.join(dir, 'package.json'));
      try {
        return require.resolve(name);
      } catch {
        return pkgPath;
      }
    }
    const parent = path.dirname(dir);
    if (parent === dir) return null;
    dir = parent;
  }
}

/** Dynamically imports vite's JS API from the project's own install. */
async function loadProjectVite(root) {
  const pkgJson = resolveProjectPackage(root, 'vite');
  if (!pkgJson) throw new Error('vite not found — run `npm install` first.');
  const entry = path.join(path.dirname(pkgJson), 'dist', 'node', 'index.js');
  return import(pathToFileURL(entry).href);
}

/** Runs a binary to completion with inherited stdio. */
function spawnInherit(bin, args) {
  return new Promise((resolve) => {
    const child = spawn(bin, args, { stdio: 'inherit' });
    child.on('exit', (code, signal) => resolve(signal ? 1 : code ?? 0));
  });
}

/** Splits `--adapter=x` / `--adapter x` out of the extra args. */
function splitAdapterFlag(extraArgs) {
  const rest = [];
  let adapter = null;
  for (let i = 0; i < extraArgs.length; i++) {
    const arg = extraArgs[i];
    if (arg === '--adapter' && extraArgs[i + 1]) {
      adapter = extraArgs[i + 1];
      i++;
    } else if (arg.startsWith('--adapter=')) {
      adapter = arg.slice('--adapter='.length);
    } else {
      rest.push(arg);
    }
  }
  return { adapter, rest };
}

/**
 * Runs the full build pipeline.
 *
 * @param options.adapterFlag — `--adapter` override (wins over astra.config.json).
 * @param options.extraArgs   — remaining args passed through to the client build.
 */
export async function buildProject({ adapterFlag = null, extraArgs = [] } = {}) {
  const root = process.cwd();
  const cfg = readProjectConfig(root);
  const adapter = adapterFlag ?? cfg.adapter ?? 'static';

  if (!ADAPTERS.includes(adapter)) {
    console.error(
      `${paint('✖', colors.red)} Unknown adapter ${paint(adapter, colors.bold)} — expected one of: ${ADAPTERS.join(', ')}`
    );
    process.exitCode = 1;
    return;
  }

  // Same deployment override the compiler plugin honors: ASTRA_API_PREFIX
  // makes the generated server entry agree with the client fetch wrappers
  // when a build is served under a sub-path.
  const apiPrefix = cfg.apiPrefix ?? process.env.ASTRA_API_PREFIX ?? '/api/astra';

  // ── 1. Client build ───────────────────────────────────────────────────
  const viteBin = findBin('vite');
  if (!viteBin) {
    console.error(`${paint('✖', colors.red)} Could not find ${paint('vite', colors.bold)} in node_modules.`);
    process.exitCode = 1;
    return;
  }
  log(`client build${extraArgs.length ? ` (${extraArgs.join(' ')})` : ''}`);
  const clientCode = await spawnInherit(viteBin, ['build', ...extraArgs]);
  if (clientCode !== 0) {
    process.exitCode = clientCode;
    return;
  }

  // ── 2. Read the server module manifest ────────────────────────────────
  const distDir = path.join(root, 'dist');
  const manifest = readJson(path.join(distDir, 'astra-server-modules.json'));
  const modulePaths = manifest ? Object.values(manifest.modules ?? {}) : [];

  if (adapter === 'static') {
    log(
      manifest
        ? 'static build complete — dynamic server() handlers need a runtime adapter (node | vercel | cloudflare).'
        : 'static build complete.'
    );
    return;
  }

  if (!manifest || modulePaths.length === 0) {
    log('no dynamic server() calls found — static output only (adapter skipped).');
    return;
  }

  // ── 3. Generate the server entry ──────────────────────────────────────
  const entryDir = path.join(root, '.astra');
  fs.mkdirSync(entryDir, { recursive: true });
  const entryPath = path.join(entryDir, 'server-entry.ts');

  const imports = modulePaths
    .map((m) => {
      const rel = String(m).replace(/^\.\//, '');
      return `import '../${rel}';`;
    })
    .join('\n');

  // AI configuration (astra.config.json `ai` section) → generated module
  // that calls configureAi() at startup. Credentials stay in env vars.
  let aiImport = '';
  if (cfg.ai) {
    const ai = cfg.ai;
    const lines = [];
    if (ai.provider) lines.push(`  provider: ${JSON.stringify(ai.provider)},`);
    if (ai.baseURL) lines.push(`  baseURL: ${JSON.stringify(ai.baseURL)},`);
    if (ai.apiKeyEnv) lines.push(`  apiKey: process.env[${JSON.stringify(ai.apiKeyEnv)}],`);
    if (ai.model) lines.push(`  model: ${JSON.stringify(ai.model)},`);
    if (ai.embedModel) lines.push(`  embedModel: ${JSON.stringify(ai.embedModel)},`);
    fs.writeFileSync(
      path.join(entryDir, 'ai-config.ts'),
      `// AUTO-GENERATED by astra build — do not edit.
import { configureAi } from 'astrajs.dev/ai';

configureAi({
${lines.join('\n')}
});
`
    );
    aiImport = `import './ai-config.js';`;
  }

  fs.writeFileSync(entryPath, TEMPLATES[adapter](imports, apiPrefix, aiImport));

  // ── 4. Server bundle (SSR pass — real handler closures) ───────────────
  const vite = await loadProjectVite(root);
  log(`server bundle (vite build --ssr → ${adapter})`);
  const ssrOutDir = path.join(entryDir, 'ssr');
  await vite.build({
    configFile: path.join(root, 'vite.config.ts'),
    root,
    logLevel: 'info',
    build: {
      ssr: entryPath,
      outDir: ssrOutDir,
      emptyOutDir: true,
      minify: false,
      target: 'es2022',
      rollupOptions: {
        output: { entryFileNames: '[name].mjs', format: 'es' },
      },
    },
    ssr: { noExternal: true },
  });

  // ── 5. Emit platform files ────────────────────────────────────────────
  const adaptersEntry = resolveProjectPackage(root, 'astrajs.dev/adapters');
  if (!adaptersEntry) {
    console.error(
      `${paint('✖', colors.red)} Adapter ${paint(adapter, colors.bold)} requires ${paint('astrajs.dev/adapters', colors.bold)} as a project dependency.`
    );
    console.error('   Install it with: npm install astrajs.dev');
    process.exitCode = 1;
    return;
  }

  const adapters = await import(pathToFileURL(adaptersEntry).href);
  const ctx = {
    root,
    distDir,
    bundlePath: path.join(ssrOutDir, 'server-entry.mjs'),
    apiPrefix,
  };

  const emit = adapters[`emit${adapter[0].toUpperCase()}${adapter.slice(1)}Adapter`];
  if (typeof emit !== 'function') {
    console.error(`${paint('✖', colors.red)} astrajs.dev/adapters does not export an emitter for ${adapter}.`);
    process.exitCode = 1;
    return;
  }

  const files = emit(ctx);
  log(`✓ ${adapter} adapter output:`);
  for (const file of files) {
    console.log(`    ${path.relative(root, file)}`);
  }
  log('deploy: see /docs/deployment in the AstraJS docs.');
}
