// AUTO-GENERATED by astra build — do not edit.
import { createServer } from 'node:http';
import { existsSync, statSync, readFileSync } from 'node:fs';
import { extname, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import { handleRPCRequest } from 'astrajs.dev/server';
import '../src/main.tsx';
import '../src/main.tsx';


const apiPrefix = "/examples/fullstack/08-autosync/api/astra";
// The bundle lives at <dist>/server/server.mjs → ../ is the client build.
const distDir = process.env.ASTRA_DIST
  ?? fileURLToPath(new URL('../', import.meta.url));
const port = Number(process.env.PORT ?? 3000);

const MIME_TYPES = {
  '.html': 'text/html; charset=utf-8',
  '.js': 'text/javascript',
  '.mjs': 'text/javascript',
  '.css': 'text/css',
  '.json': 'application/json',
  '.map': 'application/json',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.webp': 'image/webp',
  '.gif': 'image/gif',
  '.svg': 'image/svg+xml',
  '.ico': 'image/x-icon',
  '.woff': 'font/woff',
  '.woff2': 'font/woff2',
  '.ttf': 'font/ttf',
  '.txt': 'text/plain; charset=utf-8',
};

// Static file lookup with path-traversal protection.
function findStatic(pathname) {
  const rel = pathname === '/' ? 'index.html' : pathname.replace(/^\/+/, '');
  if (rel.includes('..') || rel.includes('\0')) return null;
  const base = resolve(distDir);
  const abs = resolve(base, rel);
  if (abs !== base && !abs.startsWith(base + sep)) return null;
  try {
    if (!existsSync(abs) || !statSync(abs).isFile()) return null;
  } catch {
    return null;
  }
  return {
    abs,
    type: MIME_TYPES[extname(abs).toLowerCase()] ?? 'application/octet-stream',
  };
}

// One server instance: the compiled handler modules and the RPC dispatch both
// resolve 'astrajs.dev/server' through the same module graph, so rpcHandler()
// registrations and handleRPCRequest() share a single registry.
createServer(async (req, res) => {
  try {
    const url = new URL(req.url, 'http://127.0.0.1');

    if (url.pathname === apiPrefix || url.pathname.startsWith(apiPrefix + '/')) {
      const handlerId = url.pathname.slice(apiPrefix.length + 1);
      let body;
      if (req.method !== 'GET' && req.method !== 'HEAD') {
        const chunks = [];
        for await (const c of req) chunks.push(c);
        body = Buffer.concat(chunks).toString();
      }
      const webRequest = new Request(url.toString(), {
        method: req.method,
        headers: Object.entries(req.headers).reduce(
          (acc, [k, v]) => ({
            ...acc,
            [k]: Array.isArray(v) ? v.join(', ') : String(v ?? ''),
          }),
          {}
        ),
        body,
      });
      const response = await handleRPCRequest(webRequest, handlerId);
      res.statusCode = response.status;
      response.headers.forEach((value, key) => res.setHeader(key, value));
      // Streaming handlers (aiStream) must be piped token-by-token.
      if (response.headers.get('x-astra-stream') === '1' && response.body) {
        for await (const chunk of response.body) {
          res.write(Buffer.from(chunk));
        }
        res.end();
      } else {
        res.end(Buffer.from(await response.arrayBuffer()));
      }
      return;
    }

    const file = findStatic(url.pathname);
    if (file) {
      res.statusCode = 200;
      res.setHeader('Content-Type', file.type);
      res.setHeader(
        'Cache-Control',
        url.pathname.startsWith('/assets/')
          ? 'public, max-age=31536000, immutable'
          : 'public, max-age=0, must-revalidate'
      );
      res.end(readFileSync(file.abs));
      return;
    }

    res.statusCode = 404;
    res.setHeader('Content-Type', 'application/json');
    res.end(JSON.stringify({ error: 'Not found' }));
  } catch (err) {
    res.statusCode = 500;
    res.setHeader('Content-Type', 'application/json');
    res.end(
      JSON.stringify({ error: err instanceof Error ? err.message : String(err) })
    );
  }
}).listen(port, '0.0.0.0', () => {
  console.log('[AstraJS] server listening on http://0.0.0.0:' + port);
  console.log(
    '[AstraJS] RPC prefix: ' + apiPrefix + ' · static: ' + resolve(distDir)
  );
});
