// AUTO-GENERATED by astra build — do not edit.
import { createVercelHandler } from '@astrajs/adapters';
import '../src/server.ts';
import '../src/server.ts';
import '../src/server.ts';

export default createVercelHandler({ apiPrefix: "/api/astra" });
