/**
 * @bpjs159/compiler — Resumability Transformer
 *
 * When `resumability: true` is set in astra.config.json (or plugin options),
 * this transformer scans the source for JSX event handler props and
 * auto-injects `registerHandler(fn)` calls at module level.
 *
 * The developer writes normal JSX:
 * ```tsx
 * <button onClick={handleIncrement}>+</button>
 * ```
 *
 * The compiler injects:
 * ```ts
 * import { registerHandler } from '@bpjs159/core';
 * registerHandler(handleIncrement);
 * ```
 *
 * This makes SSR resumability fully transparent — no manual
 * registerHandler() calls needed.
 */

import { ensureImport } from '../utils/ast.js';

/**
 * Result of the resumability transform.
 */
export interface ResumabilityTransformResult {
  /** The transformed source code. */
  code: string;
  /** Whether any changes were made. */
  changed: boolean;
}

/**
 * Finds function names used as JSX event handlers in the source and
 * injects `registerHandler(fn)` calls for each one.
 *
 * Handles: onClick, onInput, onChange, onSubmit, onFocus, onBlur,
 * onKeyDown, onKeyUp, onMouseEnter, onMouseLeave.
 */
export function injectRegisterHandlers(
  code: string
): ResumabilityTransformResult {
  if (!code.includes('onClick') && !code.includes('onInput') && !code.includes('onChange')) {
    return { code, changed: false };
  }

  // Strip comments before scanning so we don't match patterns in JSDoc
  // or line comments (e.g. `onClick={fn}` in a doc comment).
  const stripped = code
    .replace(/\/\*[\s\S]*?\*\//g, ' ')  // block comments → space
    .replace(/\/\/.*/g, '');            // line comments → empty

  // Match JSX event handlers with simple identifier references:
  //   onClick={handleIncrement}
  //   onInput={handleTyping}
  //   onChange={handleSelect}
  //
  // Captures the handler name (a simple identifier, not an arrow or expression).
  const handlerPattern = /\bon(?:Click|Input|Change|Submit|Focus|Blur|KeyDown|KeyUp|MouseEnter|MouseLeave)\s*=\s*\{(\w+)\s*\}/g;

  const handlerNames = new Set<string>();
  let match: RegExpExecArray | null;
  while ((match = handlerPattern.exec(stripped)) !== null) {
    handlerNames.add(match[1]!);
  }

  if (handlerNames.size === 0) return { code, changed: false };

  // Generate registerHandler calls
  const calls = Array.from(handlerNames)
    .map((name) => `registerHandler(${name});`)
    .join('\n');

  // Prepend the calls at the top of the module (after the last import)
  // Find the last import line (or use line 0 if no imports)
  const lines = code.split('\n');
  let insertAfter = 0;
  for (let i = lines.length - 1; i >= 0; i--) {
    if (/^\s*import\s+/.test(lines[i]!)) {
      insertAfter = i + 1;
      break;
    }
  }

  lines.splice(insertAfter, 0, '', '// Auto-generated by AstraJS — resumability handlers', calls);
  const transformed = lines.join('\n');

  // Ensure the import exists
  const withImport = ensureImport(transformed, 'astrajs.dev/core', ['registerHandler']);

  return { code: withImport, changed: true };
}
