"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.emitNodeAdapter = emitNodeAdapter;
exports.emitVercelAdapter = emitVercelAdapter;
exports.emitCloudflareAdapter = emitCloudflareAdapter;
exports.emitStaticAdapter = emitStaticAdapter;
/**
 * @astrajs/adapters — build-side emitters
 *
 * These functions run at BUILD time (Node.js only — never bundled into
 * edge output). Each one writes the platform-specific files for its
 * adapter, consuming the client build (`dist/`) and the bundled SSR
 * entry produced by `vite build --ssr`.
 */
var node_fs_1 = require("node:fs");
var node_path_1 = require("node:path");
var BUNDLE_PREFIX = "// AUTO-GENERATED by @astrajs/adapters \u2014 do not edit.\n";
/** Reads the SSR bundle, prepending the auto-generated banner. */
function readBundle(ctx) {
    return BUNDLE_PREFIX + (0, node_fs_1.readFileSync)(ctx.bundlePath, 'utf-8');
}
// ─── Node ────────────────────────────────────────────────────────────────────
/**
 * Node adapter: emits `dist/server/server.mjs` (standalone server) plus a
 * minimal `package.json` and a `Dockerfile`.
 */
function emitNodeAdapter(ctx) {
    var serverDir = (0, node_path_1.join)(ctx.distDir, 'server');
    (0, node_fs_1.mkdirSync)(serverDir, { recursive: true });
    var serverFile = (0, node_path_1.join)(serverDir, 'server.mjs');
    (0, node_fs_1.writeFileSync)(serverFile, readBundle(ctx));
    (0, node_fs_1.writeFileSync)((0, node_path_1.join)(serverDir, 'package.json'), JSON.stringify({ name: 'astra-node-server', private: true, type: 'module' }, null, 2) + '\n');
    var dockerfile = (0, node_path_1.join)(ctx.root, 'Dockerfile');
    if (!(0, node_fs_1.existsSync)(dockerfile)) {
        (0, node_fs_1.writeFileSync)(dockerfile, [
            '# AUTO-GENERATED by @astrajs/adapters — tune as needed.',
            'FROM node:20-alpine',
            'WORKDIR /app',
            'COPY dist ./dist',
            'ENV PORT=3000',
            'EXPOSE 3000',
            'CMD ["node", "dist/server/server.mjs"]',
            '',
        ].join('\n'));
    }
    return [serverFile, (0, node_path_1.join)(serverDir, 'package.json'), dockerfile];
}
// ─── Vercel ──────────────────────────────────────────────────────────────────
/**
 * Vercel adapter: emits `api/astra.mjs` (catch-all function) and a
 * `vercel.json` that rewrites `/api/astra/*` into it. Static assets are
 * served by Vercel automatically from the output directory.
 */
function emitVercelAdapter(ctx) {
    var apiDir = (0, node_path_1.join)(ctx.root, 'api');
    (0, node_fs_1.mkdirSync)(apiDir, { recursive: true });
    var funcFile = (0, node_path_1.join)(apiDir, 'astra.mjs');
    (0, node_fs_1.writeFileSync)(funcFile, readBundle(ctx));
    var vercelJson = (0, node_path_1.join)(ctx.root, 'vercel.json');
    if (!(0, node_fs_1.existsSync)(vercelJson)) {
        (0, node_fs_1.writeFileSync)(vercelJson, JSON.stringify({
            $schema: 'https://openapi.vercel.sh/vercel.json',
            rewrites: [{ source: '/api/astra/(.*)', destination: '/api/astra' }],
        }, null, 2) + '\n');
    }
    return [funcFile, vercelJson];
}
// ─── Cloudflare ──────────────────────────────────────────────────────────────
/**
 * Cloudflare adapter: emits `dist/_worker.js` (Pages worker) plus a
 * `wrangler.toml` template pointing Pages at `dist/`. Static assets are
 * served by the Pages asset pipeline; the Worker handles RPC.
 */
function emitCloudflareAdapter(ctx) {
    (0, node_fs_1.mkdirSync)(ctx.distDir, { recursive: true });
    var workerFile = (0, node_path_1.join)(ctx.distDir, '_worker.js');
    (0, node_fs_1.writeFileSync)(workerFile, readBundle(ctx));
    var wranglerToml = (0, node_path_1.join)(ctx.root, 'wrangler.toml');
    if (!(0, node_fs_1.existsSync)(wranglerToml)) {
        (0, node_fs_1.writeFileSync)(wranglerToml, [
            '# AUTO-GENERATED by @astrajs/adapters — tune as needed.',
            'name = "astra-app"',
            'compatibility_date = "2025-01-01"',
            '',
            '[site]',
            'bucket = "./dist"',
            '',
        ].join('\n'));
    }
    // Cloudflare Pages uses `wrangler.toml` at the repo root (pages_build_output_dir)
    // or `wrangler pages deploy dist`. Emit a helper script too.
    var deploySh = (0, node_path_1.join)(ctx.root, 'deploy.sh');
    if (!(0, node_fs_1.existsSync)(deploySh)) {
        (0, node_fs_1.writeFileSync)(deploySh, ['#!/usr/bin/env sh', 'set -e', 'npm run build', 'wrangler pages deploy dist --project-name astra-app', ''].join('\n'));
    }
    return [workerFile, wranglerToml, deploySh];
}
/** Re-exports kept for symmetry with other adapters (static needs no files). */
function emitStaticAdapter(ctx) {
    return [ctx.distDir];
}
