/**
 * astrajs.dev/adapters — build-side emitters
 *
 * These functions run at BUILD time (Node.js only — never bundled into
 * edge output). Each one writes the platform-specific files for its
 * adapter, consuming the client build (`dist/`) and the bundled SSR
 * entry produced by `vite build --ssr`.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

/**
 * Context shared by all emitters (prepared by `astra build`).
 */
export interface EmitContext {
  /** Project root (where vite.config.ts and astra.config.json live). */
  root: string;
  /** Client build output directory (usually `<root>/dist`). */
  distDir: string;
  /** Path of the built SSR bundle (single file, ESM). */
  bundlePath: string;
  /** API prefix used by the compiler for RPC endpoints. */
  apiPrefix: string;
}

const BUNDLE_PREFIX = `// AUTO-GENERATED by astrajs.dev/adapters — do not edit.\n`;

/** Reads the SSR bundle, prepending the auto-generated banner. */
function readBundle(ctx: EmitContext): string {
  return BUNDLE_PREFIX + readFileSync(ctx.bundlePath, 'utf-8');
}

// ─── Node ────────────────────────────────────────────────────────────────────

/**
 * Node adapter: emits `dist/server/server.mjs` (standalone server) plus a
 * minimal `package.json` and a `Dockerfile`.
 */
export function emitNodeAdapter(ctx: EmitContext): string[] {
  const serverDir = join(ctx.distDir, 'server');
  mkdirSync(serverDir, { recursive: true });

  const serverFile = join(serverDir, 'server.mjs');
  writeFileSync(serverFile, readBundle(ctx));

  writeFileSync(
    join(serverDir, 'package.json'),
    JSON.stringify({ name: 'astra-node-server', private: true, type: 'module' }, null, 2) + '\n'
  );

  const dockerfile = join(ctx.root, 'Dockerfile');
  if (!existsSync(dockerfile)) {
    writeFileSync(
      dockerfile,
      [
        '# AUTO-GENERATED by astrajs.dev/adapters — tune as needed.',
        'FROM node:20-alpine',
        'WORKDIR /app',
        'COPY --chown=node:node dist ./dist',
        'ENV PORT=3000 NODE_ENV=production',
        'EXPOSE 3000',
        '# SECURITY: run as the unprivileged node user, never as root.',
        'USER node',
        'CMD ["node", "dist/server/server.mjs"]',
        '',
      ].join('\n')
    );
  }

  return [serverFile, join(serverDir, 'package.json'), dockerfile];
}

// ─── Vercel ──────────────────────────────────────────────────────────────────

/**
 * Vercel adapter: emits `api/astra.mjs` (catch-all function) and a
 * `vercel.json` that rewrites `/api/astra/*` into it. Static assets are
 * served by Vercel automatically from the output directory.
 */
export function emitVercelAdapter(ctx: EmitContext): string[] {
  const apiDir = join(ctx.root, 'api');
  mkdirSync(apiDir, { recursive: true });

  const funcFile = join(apiDir, 'astra.mjs');
  writeFileSync(funcFile, readBundle(ctx));

  const vercelJson = join(ctx.root, 'vercel.json');
  if (!existsSync(vercelJson)) {
    writeFileSync(
      vercelJson,
      JSON.stringify(
        {
          $schema: 'https://openapi.vercel.sh/vercel.json',
          rewrites: [{ source: '/api/astra/(.*)', destination: '/api/astra' }],
        },
        null,
        2
      ) + '\n'
    );
  }

  return [funcFile, vercelJson];
}

// ─── Cloudflare ──────────────────────────────────────────────────────────────

/**
 * Cloudflare adapter: emits `dist/_worker.js` (Pages worker) plus a
 * `wrangler.toml` template pointing Pages at `dist/`. Static assets are
 * served by the Pages asset pipeline; the Worker handles RPC.
 */
export function emitCloudflareAdapter(ctx: EmitContext): string[] {
  mkdirSync(ctx.distDir, { recursive: true });
  const workerFile = join(ctx.distDir, '_worker.js');
  writeFileSync(workerFile, readBundle(ctx));

  const wranglerToml = join(ctx.root, 'wrangler.toml');
  if (!existsSync(wranglerToml)) {
    writeFileSync(
      wranglerToml,
      [
        '# AUTO-GENERATED by astrajs.dev/adapters — tune as needed.',
        'name = "astra-app"',
        'compatibility_date = "2025-01-01"',
        '',
        '[site]',
        'bucket = "./dist"',
        '',
      ].join('\n')
    );
  }

  // Cloudflare Pages uses `wrangler.toml` at the repo root (pages_build_output_dir)
  // or `wrangler pages deploy dist`. Emit a helper script too.
  const deploySh = join(ctx.root, 'deploy.sh');
  if (!existsSync(deploySh)) {
    writeFileSync(
      deploySh,
      ['#!/usr/bin/env sh', 'set -e', 'npm run build', 'wrangler pages deploy dist --project-name astra-app', ''].join('\n')
    );
  }

  return [workerFile, wranglerToml, deploySh];
}

/** Re-exports kept for symmetry with other adapters (static needs no files). */
export function emitStaticAdapter(ctx: EmitContext): string[] {
  return [ctx.distDir];
}
