/**
 * Template scaffolding — copies template files, replaces placeholders,
 * and (when inside the AstraJS monorepo) injects Vite aliases pointing
 * at the local packages so the app works before publish.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { colors, paint } from './colors.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const TEMPLATES_DIR = path.join(__dirname, '..', 'templates');

/**
 * Walks a directory recursively, returning relative file paths.
 */
function walk(dir, base = dir, acc = []) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      walk(full, base, acc);
    } else {
      acc.push(path.relative(base, full).split(path.sep).join('/'));
    }
  }
  return acc;
}

/**
 * Finds the AstraJS monorepo root (a dir containing packages/core) by
 * walking up from `targetDir`. Returns the relative path from the target
 * to the repo root, or null when not inside the monorepo.
 */
function findMonorepoRoot(targetDir) {
  let dir = path.resolve(targetDir);
  for (let i = 0; i < 8; i++) {
    const packagesDir = path.join(dir, 'packages');
    if (
      fs.existsSync(path.join(packagesDir, 'core', 'package.json')) &&
      fs.existsSync(path.join(packagesDir, 'compiler', 'package.json'))
    ) {
      return dir;
    }
    const parent = path.dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  return null;
}

/** Alias snippet injected into vite.config.ts when inside the monorepo. */
function monorepoAliases(targetDir) {
  const root = findMonorepoRoot(targetDir);
  if (!root) return '';
  const rel = path.relative(targetDir, root).split(path.sep).join('/');
  const base = rel === '' ? '.' : rel;
  const p = (pkg) => `path.resolve(__dirname, '${base}/packages/${pkg}/src')`;
  return `
    alias: {
      // Monorepo aliases — generated by create-astra because this project
      // lives inside the AstraJS repository. Remove them once @astrajs/*
      // packages are published to npm.
      '@astrajs/core': ${p('core')},
      '@astrajs/core/jsx-runtime': ${p('core')} + '/jsx-runtime',
      '@astrajs/core/jsx-dev-runtime': ${p('core')} + '/jsx-dev-runtime',
      '@astrajs/compiler': ${p('compiler')},
      '@astrajs/compiler/css': ${p('compiler')} + '/css',
      '@astrajs/router': ${p('router')},
      '@astrajs/server': ${p('server')},
      '@astrajs/form': ${p('form')},
      '@astrajs/schema': ${p('schema')},
      '@astrajs/validation': ${p('validation')},
      '@astrajs/ssr': ${p('ssr')},
    },`;
}

function replacePlaceholders(content, vars) {
  let out = content;
  for (const [key, value] of Object.entries(vars)) {
    out = out.split(`{{${key}}}`).join(value);
  }
  return out;
}

/**
 * Scaffolds `template` into `targetDir`.
 * Returns an array of generated file paths (relative to target).
 */
export function scaffold({ projectName, template, targetDir, packageManager, dryRun = false }) {
  const templateDir = path.join(TEMPLATES_DIR, template);
  if (!fs.existsSync(templateDir)) {
    throw new Error(`Template "${template}" not found at ${templateDir}`);
  }

  const files = walk(templateDir);
  const vars = {
    PROJECT_NAME: projectName,
    PACKAGE_MANAGER: packageManager,
  };
  const aliasSnippet = monorepoAliases(targetDir);

  if (dryRun) {
    return files.map((f) => (f === '_gitignore' ? '.gitignore' : f));
  }

  // Create the target directory
  fs.mkdirSync(targetDir, { recursive: true });

  const generated = [];
  for (const rel of files) {
    const outRel = rel === '_gitignore' ? '.gitignore' : rel;
    let content = fs.readFileSync(path.join(templateDir, rel), 'utf8');

    // Inject monorepo aliases into the vite config when applicable
    if (rel === 'vite.config.ts' && aliasSnippet) {
      content = content.replace('  __ASTRA_ALIASES__', aliasSnippet);
    } else if (rel === 'vite.config.ts') {
      content = content.replace('  __ASTRA_ALIASES__\n', '');
    }

    content = replacePlaceholders(content, vars);

    const outPath = path.join(targetDir, outRel);
    fs.mkdirSync(path.dirname(outPath), { recursive: true });
    fs.writeFileSync(outPath, content, 'utf8');
    generated.push(outRel);
  }

  return generated;
}

/** ASCII header used in --dry-run output. */
export function printFileTree(files, projectName) {
  console.log(
    `\n${paint('◇', colors.purple)} Files that would be generated in ${paint(projectName, colors.bold)}:\n`
  );
  for (const file of files.sort()) {
    const dir = file.includes('/') ? file.slice(0, file.lastIndexOf('/')) : '';
    const name = file.slice(file.lastIndexOf('/') + 1);
    console.log(
      `  ${paint(dir ? dir + '/' : '', colors.dim)}${paint(name, colors.cyan)}`
    );
  }
  console.log('');
}
